
@api = http://localhost:3000/products

###Obteniendo todas las solicitudes
GET {{api}}

###Insertando Solicitud
POST {{api}}
Content-Type: application/json

{
    "Radicado": "MVM-12345",
    "Descripcion": "Test_Litos",
    "FechaSolicitud": "2022-09-21T00:29:53.983Z",
    "FechaRespuesta": null,
    "IDResponsable": null,
    "CorreoSolicitante": "carlos@gmail.com",
    "NombreSolicitante": "Carlos",
    "ApellidoSolicitante": "berrio",
    "TelefonoSolicitante": "1234",
    "NombreEmpresa": "MVM",
    "IdTipoSolicitud": 1,
    "IDEstado": 1
} 
###Obteniendo solicitud con id
GET {{api}}/130

###Update Solicitud 
PUT {{api}}/130
Content-Type: application/json

{
    "FechaRespuesta": "2022-09-30T00:29:53.983Z",
    "IDResponsable": 3,
    "IDEstado": 2
} 


